[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pick-and-place-fault-detection-fl"
version = "1.0.0"
description = "Federated Learning for Pick-and-Place Fault Detection using Flower"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.24.0",
    "torch==2.6.0",
    "pandas>=2.0.0",
    "numpy>=1.24.0",
    "wandb",
    "seaborn>=0.12.0",
    "matplotlib>=3.7.0",
    "plotly>=5.18.0",
    "scikit-learn>=1.3.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "rluca"

[tool.flwr.app.components]
serverapp = "flower_app.server_app:app"
clientapp = "flower_app.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 100
fine-tuning-rounds = 10
fine-tuning-lr = 0.0001
fraction-fit = 1.0
local-epochs = 3
num-classes = 2
num-features = 120

[tool.flwr.federations]
default = "gpu-sim"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 2

[tool.flwr.federations.gpu-sim]
options.num-supernodes = 2
options.backend.client-resources.num-cpus = 8
options.backend.client-resources.num-gpus = 1.0